### ISSUE TITLE
All crafted items have nbt

### ISSUE THREAD

**Issue by NarwhalAndMe** [alfiae/item-modifiers#2]
All crafted items, including food items, have extra nbt applied by method "onCraft" in ItemsMixin.java

This means that items found in the world cannot be stacked with crafted items.

![image](https://github.com/alfiae/item-modifiers/assets/98322440/9ed32477-5978-45bb-8297-7881edc4f772)

![image](https://github.com/alfiae/item-modifiers/assets/98322440/17576e1d-1197-40f2-9b50-623674873838)

**Comment by alfuwu** [comment]
I knew that my solution there seemed hacky. It should be fixed with the latest commit.
